### PR TITLE
Theme update

### PR DESCRIPTION
**Pull request by oxelson**
- Modified CSS for breadcrumbs to improve usability
- Changed theme to enable 3-column layout when table of contents (toc) is enabled (otherwise is a 2 column layout).  
- Put toc in far-right column & made it "fixed" so it stays stationary on page when you scroll (as per request of @lesserwhirls).  <-- the fixed behavior may look weird if toc is long (we need to test this).
- expanded the layout to take up entire screen (max-width: 100%), but modified the footer row to retain its normal width to preserve triptych integrity.

### CODE REVIEW

**Comment by lesserwhirls** [comment]
Do you know what happened to the file `gradlew`? It looks like it was changed, sort of? Did you set the execution bit?

**Comment by lesserwhirls** [comment]
Also, I had forgotten that there was an open PR from when I was out of town (just merged it in). It was a one line change that should not impact this PR or cause any conflicts if you do a rebase against `main`.

**Comment by oxelson** [comment]
I didn't deliberately change it. 🤷‍♀️

**Comment by lesserwhirls** [comment]
One other minor thing - could you enable the TOC in `pages/unidata/markdown_overview/overview.md`? That will allow us to have an example showing the TOC in the Unidata theme portion of the docs :-)

**Comment by lesserwhirls** [comment]
> I didn't deliberately change it. 🤷‍♀️

No worries. Not sure what's up there, but it's a generated file that we can recreate if needed.

**Comment by oxelson** [comment]
> Also, I had forgotten that there was an open PR from when I was out of town (just merged it in). It was a one line change that should not impact this PR or cause any conflicts if you do a rebase against `main`.

Will do!

**Comment by oxelson** [comment]
> One other minor thing - could you enable the TOC in `pages/unidata/markdown_overview/overview.md`? That will allow us to have an example showing the TOC in the Unidata theme portion of the docs :-)

Yep! Good idea.

**Comment by oxelson** [comment]
@lesserwhirls, I added a page under the theme section describing the toc functionality (and enabled it for that page as an example).

**Review by lesserwhirls — APPROVED** [review]
Looks great! Thank you @oxelson!

**Pull request merged**
